{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-fragment-insertion
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - openjdk

  run:
    - python {{ python }}
    - openjdk
    - biom-format {{ biom_format }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - sepp
    - ijson
    # they imported a private function which doesn't exist anymore...
    # https://github.com/smirarab/sepp/blob/66cf22cfb9ca22ed9e9074984018d099617b3c6a/sepp/tree.py#L25
    - dendropy 4.5.2

test:
  requires:
    - qiime2 >={{ qiime2 }}
    - q2-types >={{ q2_types }}
    - pytest

  imports:
    - q2_fragment_insertion
    - qiime2.plugins.fragment_insertion

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
