{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-fragment-insertion
  version: {{ version }}

source:
  - path: ../..

build:
  script:
    - cp taxonomy_gg99.qza $PREFIX/share/fragment-insertion/ref/
    - make install

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - setuptools
    - fragment-insertion >=4.3.5
    - biom-format >=2.1.5,<2.2.0
    - qiime2 {{ version }}.*
    - q2-types {{ version }}.*
    - q2-feature-table {{ version }}.*

test:
  imports:
    - q2_fragment_insertion
    - qiime2.plugins.fragment_insertion

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
