{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-fragment-insertion
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools
    - openjdk

  run:
    - python {{ python }}
    - openjdk
    - biom-format >=2.1.5,<2.2.0
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*
    - sepp
    - ijson

test:
  imports:
    - q2_fragment_insertion
    - qiime2.plugins.fragment_insertion

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
