{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-fragment-insertion
  version: {{ version }}

source:
  - path: ../..
  # Not using the built-in patching mechanism of conda-build, since we aren't
  # actually patching q2-fragment-insertion, but rather sepp-refs.
  - path: reloc.patch
  - path: indent.patch

requirements:
  build:
    - python {{ python }}
    - setuptools
    - java-jdk

  run:
    - python {{ python }}
    - java-jdk
    - biom-format >=2.1.5,<2.2.0
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_fragment_insertion
    - qiime2.plugins.fragment_insertion

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
