{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}
{% set release = '.'.join(version.split('.')[:2]) %}

package:
  name: q2-fragment-insertion
  version: {{ version }}

source:
  - path: ../..
  - path: reloc.patch
  - path: indent.patch

requirements:
  build:
    - python 3.5*
    - setuptools
    # TODO: Necessary?
    - java-jdk

  run:
    - python 3.5*
    - setuptools
    # TODO: Necessary?
    - java-jdk
    - biom-format >=2.1.5,<2.2.0
    - qiime2 {{ release }}.*
    - q2-types {{ release }}.*

test:
  imports:
    - q2_fragment_insertion
    - qiime2.plugins.fragment_insertion

about:
  home: https://qiime2.org
  license: BSD-3-Clause
  license_family: BSD
